const CACHE_NAME = 'gold-price-v36-stable-yahoo-json';
const STATIC_CACHE = [
  './manifest.json',
  'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@300;400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap'
];

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(STATIC_CACHE)).catch(() => {}));
  self.skipWaiting();
});

self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(names => Promise.all(names.filter(n => n !== CACHE_NAME).map(n => caches.delete(n)))));
  self.clients.claim();
});

function isYahooDataFile(url){
  return url.origin === self.location.origin && /\/data\/yahoo-gold\.json$/i.test(url.pathname);
}

function isBlockedLegacyRemote(url){
  return /finance\/chart|allorigins|corsproxy|codetabs|isomorphic-git|cors\.isomorphic|tradingview|coingecko/i.test(url.href);
}

function isNoCacheApi(url){
  return /gold-api|open\.er-api|currency-api|firebaseio|gstatic\.com\/firebase/i.test(url.href);
}

async function networkFirst(request){
  const cache = await caches.open(CACHE_NAME);
  try{
    const fresh = await fetch(request, { cache:'no-store' });
    if(fresh && fresh.ok) cache.put(request, fresh.clone()).catch(() => {});
    return fresh;
  }catch(_){
    return (await cache.match(request)) || (await cache.match('./index.html')) || new Response('', {status:204});
  }
}

async function staleWhileRevalidate(request){
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  const update = fetch(request).then(res => {
    if(res && res.ok) cache.put(request, res.clone()).catch(() => {});
    return res;
  }).catch(() => null);
  return cached || update || fetch(request).catch(() => new Response('', {status:204}));
}

self.addEventListener('fetch', event => {
  const req = event.request;
  if(req.method !== 'GET') return;
  const url = new URL(req.url);

  // v36: if an old cached page still tries Yahoo/proxy/TradingView/CoinGecko,
  // answer locally so the browser does not show CORS/popup/network spam.
  if(isBlockedLegacyRemote(url)){
    event.respondWith(new Response(JSON.stringify({blocked:true, reason:'legacy remote disabled by v36'}), {
      status:200,
      headers:{
        'Content-Type':'application/json; charset=utf-8',
        'Cache-Control':'no-store',
        'Access-Control-Allow-Origin':'*'
      }
    }));
    return;
  }

  // Same-origin Yahoo mirror generated by GitHub Actions; always try network first.
  if(isYahooDataFile(url)){
    event.respondWith(networkFirst(req));
    return;
  }

  // Never cache live price/rate/firebase reads, but do not throw Response.error().
  if(isNoCacheApi(url)){
    event.respondWith(fetch(req, { cache:'no-store' }).catch(() => new Response('', {status:204})));
    return;
  }

  if(req.mode === 'navigate' || url.pathname.endsWith('/index.html') || url.pathname === '/' || url.pathname.endsWith('/gold/')){
    event.respondWith(networkFirst(req));
    return;
  }

  if(url.origin === self.location.origin || url.hostname.includes('fonts.googleapis.com') || url.hostname.includes('fonts.gstatic.com')){
    event.respondWith(staleWhileRevalidate(req));
  }
});
